# Generated by Django 6.0.4 on 2026-04-17 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protinidi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('mobile', models.CharField()),
                ('exam_id', models.CharField()),
                ('user_id', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(blank=True, null=True)),
                ('education', models.CharField(blank=True, null=True)),
                ('date_of_birth', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.CharField()),
                ('test_mark', models.CharField(blank=True, null=True)),
                ('viva_mark', models.CharField(blank=True, null=True)),
                ('behaviour_mark', models.CharField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='main.protinidi')),
            ],
        ),
    ]
