# Generated by Django 6.0.4 on 2026-04-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_filefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='filefield',
            name='title',
            field=models.CharField(default='null'),
            preserve_default=False,
        ),
    ]
